project_汎用ビュー化する前/diary/urls.py
from django.urls import path
from .import views

app_name = 'diary'

urlpatterns = [
    path("", views.index, name='index'), #/diaryのときに読まれるだけ
    path("add/", views.add, name='add'),
    #updateの後はpkにあるintなら何でも良いよ
    path("update/<int:pk>", views.update, name='update'),
    path("delete/<int:pk>", views.delete, name='delete'),
    path("detail/<int:pk>", views.detail, name='detail'),
]

project_汎用ビュー化する前/project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('diary/', include('diary.urls')),
]

project_汎用ビュー化する前/diary/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class Day(models.Model):
    #id = models.AutoField(primary_key=True)これは自動で作成されるから書かなくても良い
    title = models.CharField('タイトル', max_length=200)
    text = models.TextField('本文')
    date = models.DateTimeField('日付', default = timezone.now)

project_汎用ビュー化する前/diary/forms.py
'''
htmlのinputを作っていくのは面倒だから
値のバリデーションまでしてくれるから
day_form.htmlで使っている
'''
from django import forms
from .models import Day

class DayCreateForm(forms.ModelForm):

    class Meta:
        model = Day
        fields = '__all__'

project_汎用ビュー化する前/diary/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import DayCreateForm
from .models import Day

# Create your views here.
def index(request):
    context = {
        'day_list':Day.objects.all(),
    }
    return render(request, 'diary/day_list.html', context)

def add(request):
    form = DayCreateForm(request.POST or None)

    #methodがPOSTで、データも正しい場合
    if request.method == 'POST' and form.is_valid():
        form.save()
        #postがうまくいったらredirectさせないと、二重投稿される原因になる
        return redirect('diary:index')

    context = {
        'form': DayCreateForm()
    }
    return render(request, 'diary/day_form.html', context)

def update(request, pk):
    day = get_object_or_404(Day, pk=pk)
    #pkのなかにあるものだったらobjectを返すし、なかったら404
    form = DayCreateForm(request.POST or None, instance=day)

    if request.method == 'POST' and form.is_valid():
        form.save()
        return redirect('diary:index')
    context = {
        'form':form
    }
    return render(request, 'diary/day_form.html', context)

def delete(request, pk):
    day = get_object_or_404(Day, pk=pk)
    #pkのなかにあるものだったらobjectを返すし、なかったら404

    if request.method == 'POST':
        day.delete()
        return redirect('diary:index')
    context = {
        'day':day
    }
    return render(request, 'diary/day_confirm_delete.html', context)

def detail(request, pk):
    day = get_object_or_404(Day, pk=pk)
    #pkのなかにあるものだったらobjectを返すし、なかったら404

    context = {
        'day':day
    }
    return render(request, 'diary/day_detail.html', context)

project_汎用ビュー化する前/diary/templates/day_form.html
{% extends 'diary/base.html' %}

{% block content %}
<form action="" method="POST">
  <!--入力欄がpタグになるようにas_pとしている-->
  {{form.as_p}}
  <button type="submit">送信</button>
  <!--クロスサイトリクエスト、POSTの時は必須。GETは別に良い-->
  {% csrf_token %}
  </form>
  {% endblock %}

project_汎用ビュー化する前/diary/templates/diary/base.html
<!doctype html>
<html lang="ja">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>Dialy</title>
  </head>
  <body>


  <nav class="nav">
  <a class="nav-link active" href="{% url 'diary:index' %}">一覧</a>
    <marquee behavior="alternate" direction="up" height="100"><marquee direction="right">　♪♪♪</marquee></marquee>
    <marquee behavior="alternate"loop="100" width="500" onmouseover="this.style.filter='Glow(Color=yellow　Strength=25)';this.loop='100'" onmouseout="this.style.filter='';this.loop='100'">
        <font size=7>☆AYUMIN☆</font>
    </marquee>

    <marquee behavior="alternate" direction="up" height="100"><marquee direction="right">　♪♪♪</marquee></marquee>

  <a class="nav-link" href="{% url 'diary:add' %}">追加</a>
</nav>

    {% block content %}
    {% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    {% block script %}
    {% endblock %}
  </body>
</html>

project_汎用ビュー化する前/diary/templates/diary/day_confirm_delete.html
{% extends 'diary/base.html' %}

{% block content %}
<form action="" method="POST">
  <table class="table">
    <tr>
      <th>title</th>
      <td>{{day.text}}</td>
    </tr>
    <tr>
      <th>text</th>
      <td>{{day.text}}</td>
    </tr>
    <tr>
      <th>date</th>
      <td>{{day.date}}</td>
    </tr>
  </table>

  <p>こちらのデータを削除します</p>
  <button type="submit">送信</button>
  <!--クロスサイトリクエスト、POSTの時は必須。GETは別に良い-->
  {% csrf_token %}
  </form>
  {% endblock %}

project_汎用ビュー化する前/diary/templates/diary/day_detail.html
{% extends 'diary/base.html' %}

{% block content %}
<form action="" method="POST">
  <table class="table">
    <tr>
      <th>title</th>
      <td>{{day.title}}</td>
    </tr>
    <tr>
      <th>text</th>
      <td>{{day.text | linebreaksbr}}</td>
    </tr>
    <tr>
      <th>date</th>
      <td>{{day.date}}</td>
    </tr>
  </table>
  </form>
  {% endblock %}

project_汎用ビュー化する前/diary/templates/diary/day_form.html
{% extends 'diary/base.html' %}

{% block content %}
<form action="" method="POST">
  {{form.as_p}}
  <button type="submit">送信</button>
  {% csrf_token%}
  </form>
  {% endblock %}

project_汎用ビュー化する前/diary/templates/diary/day_list.html
{% extends 'diary/base.html' %}

{% block content %}
<h1>日記一覧</h1>
<table class="table">
  <thread>
    <tr>
      <th>タイトル</th>
      <th>date</th>
    </tr>
  </thread>
  <tbody>
    {% for day in day_list %}
    <tr>
      <td><a href="{% url 'diary:detail' day.pk %}"</a>{{day.title}}</td>
      <td>{{day.date}}</td>
      <!--pkはprimary keyなので、絶対に生成されている-->
      <td><a href="{% url 'diary:update' day.pk %}">更新</a></td>
      <td><a href="{% url 'diary:delete' day.pk %}">削除</a></td>
    </tr>
{% endfor %}
</tbody>
</table>

{% endblock %}